export const SET_SCHEDULES = 'SET_SCHEDULES';
export const CHANGE_SCHEDULE = 'CHANGE_SCHEDULE';
export const ADD_SCHEDULE = 'ADD_SCHEDULE';
export const SET_SCHEDULE = 'SET_SCHEDULE';
export const SET_SCHEDULE_TASKS = 'SET_SCHEDULE_TASKS';
export const START_LOADING_SCHEDULES = 'START_LOADING_SCHEDULES';
export const STOP_LOADING_SCHEDULES = 'STOP_LOADING_SCHEDULES';