export const SET_CHECK_IN_REPORTS = 'SET_CHECK_IN_REPORTS';
export const START_LOADING_CHECK_IN_REPORTS = 'START_LOADING_CHECK_IN_REPORTS';
export const STOP_LOADING_CHECK_IN_REPORTS = 'STOP_LOADING_CHECK_IN_REPORTS';