export const SET_ACTION_REPORTS = 'SET_ACTION_REPORTS';
export const START_LOADING_ACTION_REPORTS = 'START_LOADING_ACTION_REPORTS';
export const STOP_LOADING_ACTION_REPORTS = 'STOP_LOADING_ACTION_REPORTS';