export const SET_PRODUCTS = 'SET_PRODUCTS';
export const CHANGE_PRODUCT = 'CHANGE_PRODUCT';
export const ADD_PRODUCT = 'ADD_PRODUCT'; 
export const START_LOADING_PRODUCTS = 'START_LOADING_PRODUCTS';
export const STOP_LOADING_PRODUCTS = 'STOP_LOADING_PRODUCTS';