export const SET_TOWN = 'SET_TOWN';
export const ADD_TOWN = 'ADD_TOWN';
export const CHANGE_TOWN_STATUS = 'CHANGE_TOWN_STATUS';
export const SET_TOWNS = 'SET_TOWNS';
export const START_LOADING_TOWNS = 'START_LOADING_TOWNS';
export const STOP_LOADING_TOWNS = 'STOP_LOADING_TOWNS';
export const SET_FILTERED_TOWNS = 'SET_FILTERED_TOWNS';
