import React from 'react';
import dayjs from 'dayjs';
import relativeTime from 'dayjs/plugin/relativeTime';
import {Link} from 'react-router-dom';

//MUI 
import withStyles from '@material-ui/core/styles/withStyles';
import Card from '@material-ui/core/Card';
import CardContent from '@material-ui/core/CardContent';
import CardActions from '@material-ui/core/CardActions';
import Typography from '@material-ui/core/Typography';
import Divider from '@material-ui/core/Divider';
import Button from '@material-ui/core/Button';

//Icons
import AccessTimeIcon from '@material-ui/icons/AccessTime';
import AssignmentIndIcon from '@material-ui/icons/AssignmentInd';
import ContactsIcon from '@material-ui/icons/Contacts';
import AccountBalanceIcon from '@material-ui/icons/AccountBalance';
import Looks4Icon from '@material-ui/icons/Looks4';

const styles = theme => ({
    infoContainer: {
        position: 'relative',
    },
    lightTitle: {
        position: 'absolute',
        right: 10,
        marginBottom: 20,
        [theme.breakpoints.down("md")]: {
            display: 'none'
        }
    },
    item: {
        display: 'flex',
        flexDireaction: 'row',
        margin: 10
    },
    note: {
        marginLeft: 20,
    }
});


const Task = ({classes, task}) => {
    
    dayjs.extend(relativeTime);
    const {department_name, description,number_of_actions, status, task_name} = task;
    return (
        <Card>
            <CardContent className={classes.infoContainer}>
                {/* <Typography vairant="body2" color="textSecondary" className={classes.lightTitle}>
                    <i>This schedule was generated by {created_by === agent_id ? "an agent" : "the office"} {dayjs(created_at._seconds * 1000).fromNow()}</i>
                </Typography> */}
                <div className={classes.item}>
                {/* <AccessTimeIcon color={status === 'pending' ? 'secondary' : status === 'started' ? 'primary' : ''} /> <span className={classes.note}>Visit Date <strong>{dayjs(visit_date._seconds * 1000).format('h: mm a, MMMM DD YYYY')} ({status})</strong></span> */}
                </div>
                <div className={classes.item}>
                    <AssignmentIndIcon color="primary" /> <span className={classes.note}> Department Name: <strong>{department_name}</strong> </span>
                </div>
                <div className={classes.item}>
                    <ContactsIcon color="primary" /> <span className={classes.note}>Task Description <strong>{description}</strong> </span>
                </div>
                <div className={classes.item}>
                    <ContactsIcon color="primary" /> <span className={classes.note}> Action Number <strong>{number_of_actions}</strong> </span>
                </div>
                <div className={classes.item}>
                    <AccountBalanceIcon color="primary" /> <span className={classes.note}> Task Status <strong>{status}</strong> </span>
                </div>
                <div className={classes.item}>
                    <AccountBalanceIcon color="primary" /> <span className={classes.note}>Task Name <strong>{task_name}</strong> </span>
                </div>
            </CardContent>
            <Divider />
            <CardActions>
                <Button
                variant="contained"
                color="primary"
                component={Link}
                to="/tasks"
                >Back</Button>
            </CardActions>
        </Card>
    )
}

export default withStyles(styles)(React.memo(Task));
