import React from 'react';
import {Link} from 'react-router-dom';
import dayjs from 'dayjs';
import relativeTime from 'dayjs/plugin/relativeTime';

//MUI
import withStyles from '@material-ui/core/styles/withStyles';
import Typography from '@material-ui/core/Typography';
import Card from '@material-ui/core/Card';
import CardContent from '@material-ui/core/CardContent';
import Divider from '@material-ui/core/Divider';
import CardActions from '@material-ui/core/CardActions';
import Button from '@material-ui/core/Button';

//Icons
import AccessTimeIcon from '@material-ui/icons/AccessTime';
import Looks3Icon from '@material-ui/icons/Looks3';
import Looks4Icon from '@material-ui/icons/Looks4';
import DonutLargeIcon from '@material-ui/icons/DonutLarge';
import AddLocationIcon from '@material-ui/icons/AddLocation';
import AssignmentIndIcon from '@material-ui/icons/AssignmentInd';
import ContactsIcon from '@material-ui/icons/Contacts';
import AccountBalanceIcon from '@material-ui/icons/AccountBalance';

const styles = theme => ({
    detailsContainer: {
        marginBottom: 10,
    },
    infoContainer: {
        position: 'relative',
        marginBottom: 10,
        padding: 5,
        display: 'flex',
        flexDirection: 'row',
        flexWrap: 'wrap',
    },
    lightTitle: {
        position: 'absolute',
        right: 10,
        marginBottom: 20,
        [theme.breakpoints.down("md")]: {
            display: 'none'
        }
    },
    item: {
        display: 'flex',
        flexDirection: 'row',
        margin: 10,
        width: '40%',
    },
    note: {
        marginLeft: 20,
    }
});

const VisitReportDetails = ({classes, report, handleClose}) => {
    dayjs.extend(relativeTime);

    const { created_by, agent_id, visit_date, number_of_tasks, status, start_time, end_time, customer_name, customer_address, department_name, completed_task_ids, proximity_in_meters} = report;
    return (
        <Card className={classes.detailsContainer}>
                    <CardContent className={classes.infoContainer}>
                        <Typography vairant="body2" color="textSecondary" className={classes.lightTitle}>
                            <i>This schedule was generated by {created_by === agent_id ? "an agent" : "the office"} </i>
                        </Typography>
                        <div className={classes.item}>
                            <AccessTimeIcon color={status === 'pending_completion' ? 'secondary' : 'primary'} /> <span className={classes.note}>Visit Date <strong>{dayjs(visit_date._seconds * 1000).format('h: mm a, MMMM DD YYYY')} ({status})</strong></span>
                        </div>
                        <div className={classes.item}>
                            <span className={classes.note}>Started <strong>{dayjs(start_time._seconds * 1000).fromNow()} </strong></span>
                            {end_time ? <span className={classes.note}>Ended <strong>{dayjs(end_time._seconds * 1000).fromNow()} </strong></span> : <span>Still in Progress</span> }
                        </div>
                        <div className={classes.item}>
                            <Looks3Icon color="primary" /> <span className={classes.note}> Number of Tasks <strong>{number_of_tasks}</strong> </span>
                        </div>
                        <div className={classes.item}>
                            <AssignmentIndIcon color="primary" /> <span className={classes.note}> Customer <strong>{customer_name}</strong> </span>
                        </div>
                        <div className={classes.item}>
                            <ContactsIcon color="primary" /> <span className={classes.note}> Customer Address <strong>{customer_address}</strong> </span>
                        </div>
                        <div className={classes.item}>
                            <AccountBalanceIcon color="primary" /> <span className={classes.note}> Department <strong>{department_name}</strong> </span>
                        </div>
                        <div className={classes.item}>
                            <Looks4Icon color="primary" /> <span className={classes.note}> Completed Tasks <strong>{completed_task_ids ? completed_task_ids.length : 0}</strong> </span>
                        </div>
                        <div className={classes.item}>
                            <DonutLargeIcon color="primary" /> <span className={classes.note}> Percentage Complete <strong>{completed_task_ids ? completed_task_ids.length / number_of_tasks * 100 : 0}%</strong> </span>
                        </div>
                        <div className={classes.item}>
                            <AddLocationIcon color="primary" /> <span className={classes.note}> Proximity <strong>{proximity_in_meters} meters</strong> </span>
                        </div>
                    </CardContent>
                    <Divider />
                    <CardActions>
                        <Button
                        variant="contained"
                        color="primary"
                        onClick={handleClose}
                        >Back</Button>
                    </CardActions>
                </Card>
    )
}

export default withStyles(styles)(React.memo(VisitReportDetails));
