export const SET_CUSTOMERS = 'SET_CUSTOMERS';
export const SET_CUSTOMER = 'SET_CUSTOMER';
export const CHANGE_CUSTOMER = 'CHANGE_CUSTOMER';
export const ADD_CUSTOMER = 'ADD_CUSTOMER';
export const START_LOADING_CUSTOMERS = 'START_LOADING_CUSTOMERS';
export const STOP_LOADING_CUSTOMERS = 'STOP_LOADING_CUSTOMERS';
export const SET_FILTERED_CUSTOMERS = 'SET_FILTERED_CUSTOMERS';