export const SET_SUPERVISOR = 'SET_SUPERVISOR';
export const CHANGE_SUPERVISOR_STATUS = 'CHANGE_SUPERVISOR_STATUS';
export const SET_SUPERVISORS = 'SET_SUPERVISORS';
export const START_LOADING_SUPERVISORS = 'START_LOADING_SUPERVISORS';
export const STOP_LOADING_SUPERVISORS = 'STOP_LOADING_SUPERVISORS';
export const SET_FILTERED_SUPERVISORS = 'SET_FILTERED_SUPERVISORS';
export const SET_SUPERVISOR_AGENTS ='SET_SUPERVISOR_AGENTS';
