export const SET_REGION = 'SET_REGION';
export const ADD_REGION = 'ADD_REGION';
export const CHANGE_REGION_STATUS = 'CHANGE_REGION_STATUS';
export const SET_REGIONS = 'SET_REGIONS';
export const START_LOADING_REGIONS = 'START_LOADING_REGIONS';
export const STOP_LOADING_REGIONS = 'STOP_LOADING_REGIONS';
