export const SET_PRODUCT_CATEGORIES = 'SET_PRODUCT_CATEGORIES';
export const CHANGE_PRODUCT_CATEGORY = 'CHANGE_PRODUCT_CATEGORY';
export const ADD_PRODUCT_CATEGORY = 'ADD_PRODUCT_CATEGORY';
export const START_LOADING_PRODUCT_CATEGORIES = 'START_LOADING_PRODUCT_CATEGORIES';
export const STOP_LOADING_PRODUCT_CATEGORIES = 'STOP_LOADING_PRODUCT_CATEGORIES';