export const SET_DEPARTMENTS = 'SET_DEPARTMENTS';
export const CHANGE_DEPARTMENTS = 'CHANGE_DEPARTMENTS';
export const START_LOADING_DEPARTMENTS = 'START_LOADING_DEPARTMENTS';
export const STOP_LOADING_DEPARTMENTS = 'STOP_LOADING_DEPARTMENTS';