export const SET_TERRITORIES = 'SET_TERRITORIES';
export const CHANGE_TERRITORY = 'CHANGE_TERRITORY';
export const ADD_TERRITORY = 'ADD_TERRITORY'
export const START_LOADING_TERRITORIES = 'START_LOADING_TERRITORIES';
export const STOP_LOADING_TERRITORIES = 'STOP_LOADING_TERRITORIES';